version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db  # Use o nome do serviço do MySQL como hostname
      - DB_USER=root # Substitua pelo seu usuario
      - DB_PASS=aluno # Substitua pela sua senha
      - DB_NAME=agenda_contatos # Substitua pelo seu banco de dados
  db:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=aluno # Substitua pela sua senha root
      - MYSQL_DATABASE=agenda_contatos # Substitua pelo seu banco de dados
      - MYSQL_USER=root # Substitua pelo seu usuario
      - MYSQL_PASSWORD=aluno # Substitua pela sua senha
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mapeia o arquivo init.sql
    ports:
      - "3306:3306"
volumes:
  db_data: